### ISSUE TITLE
Unable to specify server port

### ISSUE THREAD

**Issue by sdalexandre** [Unity-Technologies/unity-cache-server#66] opened 2018-11-07 23:34 UTC
Trying to import a project to cache server by specifying a server port number returns:
unity-cache-server-import CacheServerTransactions_Android.json 192.168.1.203:8126
IPV6 mirrors not supported

Fortunately, we are using the default port so not specifying the port works:
unity-cache-server-import CacheServerTransactions_Android.json 192.168.1.203

But eventually if we want to have one instance per project, we will have to use another port.

**Comment by stephen-palmer** [comment] 2018-11-16 20:53
Yes, I found the root cause of this bug while doing some refactoring for the next release. It's fixed in the master branch.

**Closed** 2018-12-14 17:16 UTC
Labels: bug
